#Setting up UBUNTU 16.04 and CUDA for Deep learning using python

$ sudo apt-get update
$ sudo apt-get upgrade

# installing some necessary development tools, image/video I/O, GUI operations and various other packages

$ sudo apt-get install build-essential cmake git unzip pkg-config
$ sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
$ sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
$ sudo apt-get install libxvidcore-dev libx264-dev
$ sudo apt-get install libgtk-3-dev
$ sudo apt-get install libhdf5-serial-dev graphviz
$ sudo apt-get install libopenblas-dev libatlas-base-dev gfortran
$ sudo apt-get install python-tk python3-tk python-imaging-tk

# installing both Python 2.7 and Python 3 header files

$ sudo apt-get install python2.7-dev python3-dev

	
$ pip install numpy

$ cd ~
$ wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.3.0.zip
$ wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/3.3.0.zip
$ unzip opencv.zip
$ unzip opencv_contrib.zip

# Install Keras
$ pip install scipy matplotlib pillow
$ pip install imutils h5py requests progressbar2
$ pip install scikit-learn scikit-image
$ pip install tensorflow-gpu
$ pip install keras


